name: gtk_flutter
description: "Get to know Firebase with Flutter"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  intl: any
  cached_network_image: ^3.4.1
  dio: ^5.0.1

  equatable: ^2.0.3
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.1
  firebase_ui_auth: ^1.15.0
  firebase_ui_localizations: ^1.2.0
  firebase_ui_firestore: ^1.6.3
  firebase_ui_oauth_google: ^1.3.3
  firebase_ui_oauth_apple: ^1.2.21
  firebase_ui_oauth_facebook: ^1.2.21
  firebase_storage: ^12.2.0

  flutter_cache_manager: ^3.4.1
  flutter_tags: 1.0.0-nullsafety.1
  flutter_social_button: any
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.2.0
  go_router: ^14.0.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.6.1
  introduction_screen: ^3.1.14
  image_picker: ^1.1.2
  json_annotation: ^4.0.1
  placeholder_images: ^0.0.1
  riverpod_annotation: ^2.6.1
  rxdart: ^0.27.7
  shared_preferences: ^2.3.0
  settings_ui: ^2.0.2
  table_calendar: ^3.1.2
  geolocator: ^13.0.1
  flutter_platform_alert: ^0.6.1
  awesome_dio_interceptor: ^1.3.0
  envied: ^1.0.0
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  intl_translation: ^0.20.1
  flutter_hooks: ^0.20.5
  redacted: ^1.0.12
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.1
  flutter_map_location_marker: ^9.1.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  flex_color_scheme: ^8.0.2
  url_launcher: ^6.3.1
  flutter_settings_ui: ^3.0.1
  path_provider: ^2.1.5
  drift: ^2.23.0
  drift_flutter: ^0.1.0
  logger: ^2.5.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.23.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1
  envied_generator: ^1.0.0
# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/icon.png
    - assets/images/splash.png
    - assets/images/image_placeholder.png
    - assets/images/splash_image.png

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf